### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by ItsShawn** [ItsShawn/scripturealone.app#2]
When a user enters the name of a book, chapter, and verse, and toggle their version of preference on the right of the search bar, it will load a new page with their result

**Comment by yonderbread** [comment]
This is a much smaller piece of the puzzle than I think you realize. We will need to set up a database backend as well as routing for all the views and client interfaces.

**Comment by yonderbread** [comment]
I'm going to close this since this issue's topic falls under #4
