### ISSUE TITLE
Dropdown Button

### ISSUE THREAD

**Issue by ItsShawn** [ItsShawn/scripturealone.app#3]
Dropdown Button:
When a user clicks on the chapter of a book, it will push them down to the list of chapters for that book

(the above part has been completed already)

Once they click on the chapter, a new page loads with the book and full chapter that they selected
https://biblegateway.com/ you can test and see what I'm talking about by testing with the search bar, the version toggle, and the Bible book list dropdown below the search bar

**Comment by yonderbread** [comment]
Please see https://github.com/ItsShawn/itsshawn.github.io/issues/2#issuecomment-1014965000
