### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by yonderbread** [ItsShawn/scripturealone.app#4]
_Let's try to plan out the different components and user interfaces that will be required for this web application._

**Major Components:**
- Search Page
- Index Lists
  - Bookmarks
  - Bible Version
  - Chapter & Verse Selection
  - Bible text view
  - Settings

**Topics That Need Further Discussion:**
- How should each page be laid out?
- Are they any backend services we need? Can we come up with some standardized schemas to create database tables from? What parts of the UI link to what?
- For our database, what would be the best way to store Bible content data that the web app can retrieve?

**Comment by yonderbread** [comment]
I think the most important task at hand is planning out the UI. With solid prototypes and designs we can derive the rest of our requirements related to the actual backend database and server-side logic.

**Comment by ItsShawn** [comment]
#1: I have gotten access to figma license and I will be working on new designs to use for the site. I will share them with you once I am finished (this might take a week or so)
#2: By services, I am not sure if we need anything other than the sword engine, but I do plan to have the following:

1. Bible Plans
2. Audio/Video Sermons

For the Bible Plans, I can store that locally for now, however we might need to set something up so users can create their own accounts and track their reading progress and things like that.

For the audio/video sermons, we will need to find something for that like a CDN as I mentioned before.

**Comment by yonderbread** [comment]
> #2: By services, I am not sure if we need anything other than the sword engine

Well, I'm pretty sure the sword engine is a server-side framework because sending the entirity of the bible with the web page requests would use a lot of data and just wouldn't make much sense. Instead, it would be better to just send the requested parts. We don't need to worry too much about this at the moment the time will come for it later.

> For the Bible Plans, I can store that locally for now, however we might need to set something up so users can create their own accounts and track their reading progress and things like that.

Probably best if we use something like Firebase to store user data. That way, we won't need to actually provide an API backend for the user services. The client would authenticate with OAuth2 callbacks and all the data handling would be done on Google's side and sent back if needed.

> For the audio/video sermons, we will need to find something for that like a CDN as I mentioned before.

Depending on what you mean, and I'm sort of just guessing what you are wanting done here and suggesting a solution, but we could just use the YouTube API and query related videos based on keywords found in selected Bible passages.

**Comment by ItsShawn** [comment]
So right now do you suggest that I first create the UI of how the site should look in its entirety before we start any actual work?

**Comment by yonderbread** [comment]
Yes, unless you would like to work on [writing up requirement documentation](https://www.perforce.com/blog/alm/how-write-software-requirements-specification-srs-document) beforehand.

**Comment by yonderbread** [comment]
From how you've described your vision of this project to me previously, it sounds like it's going to be a rather significant task to complete. It would be a good idea to write up some requirements so that there is a clear understanding of what will need to get accomplished and in what order. Before we work on development, defining guidelines and goals for ourselves and the project is very important so that we finish things as swiftly and effectively as possible.

**Comment by yonderbread** [comment]
Revised my [response](https://github.com/ItsShawn/itsshawn.github.io/issues/4#issuecomment-1015873307) to [your question from earlier](https://github.com/ItsShawn/itsshawn.github.io/issues/4#issuecomment-1015326739).

**Comment by yonderbread** [comment]
@ItsShawn
